#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(dirname "$SCRIPT_DIR")"

# Activate Ansible venv if ansible-playbook is not in PATH
if ! command -v ansible-playbook &>/dev/null; then
  if [ -f "$HOME/.ansible-venv/bin/activate" ]; then
    source "$HOME/.ansible-venv/bin/activate"
  else
    echo "Error: ansible-playbook not found. Install Ansible or create venv at ~/.ansible-venv" >&2
    exit 1
  fi
fi

echo "=== OpenClaw DigitalOcean Deploy ==="
echo ""

# Step 1: Terraform
echo "[1/3] Provisioning infrastructure with Terraform..."
cd "$ROOT_DIR/terraform"

terraform init -input=false
terraform apply -auto-approve

DROPLET_IP=$(terraform output -raw droplet_ip)
SSH_PRIV_KEY=$(terraform output -raw ssh_private_key_path)
echo "Droplet IP: $DROPLET_IP"
echo "Inventory and vars files generated by Terraform."

# Step 2: Wait for SSH (openclaw user created by cloud-init at boot)
echo ""
echo "[2/3] Waiting for SSH to become available..."
for i in $(seq 1 30); do
  if ssh -i "$SSH_PRIV_KEY" -o StrictHostKeyChecking=no -o ConnectTimeout=5 openclaw@"$DROPLET_IP" true 2>/dev/null; then
    echo "  Connected."
    break
  fi
  echo "  Attempt $i/30 — waiting..."
  sleep 10
done

echo ""
echo "[3/3] Running Ansible playbook..."
cd "$ROOT_DIR/ansible"
ansible-playbook -i inventory.ini playbook.yml "$@"

echo ""
echo "=== Deploy complete! ==="
terraform -chdir="$ROOT_DIR/terraform" output
